package pojo;
// Generated Dec 31, 2018 12:01:50 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {


     private Integer idDisciplina;
     private Studenti studentiByStudentiIdstudenti;
     private Studenti studentiByIdstudenti;
     private Subiecte subiecte;
     private Date dataExamen;
     private Integer puncteCredit;

    public Disciplina() {
    }

	
    public Disciplina(Studenti studentiByStudentiIdstudenti, Studenti studentiByIdstudenti, Subiecte subiecte) {
        this.studentiByStudentiIdstudenti = studentiByStudentiIdstudenti;
        this.studentiByIdstudenti = studentiByIdstudenti;
        this.subiecte = subiecte;
    }
    public Disciplina(Studenti studentiByStudentiIdstudenti, Studenti studentiByIdstudenti, Subiecte subiecte, Date dataExamen, Integer puncteCredit) {
       this.studentiByStudentiIdstudenti = studentiByStudentiIdstudenti;
       this.studentiByIdstudenti = studentiByIdstudenti;
       this.subiecte = subiecte;
       this.dataExamen = dataExamen;
       this.puncteCredit = puncteCredit;
    }
   
    public Integer getIdDisciplina() {
        return this.idDisciplina;
    }
    
    public void setIdDisciplina(Integer idDisciplina) {
        this.idDisciplina = idDisciplina;
    }
    public Studenti getStudentiByStudentiIdstudenti() {
        return this.studentiByStudentiIdstudenti;
    }
    
    public void setStudentiByStudentiIdstudenti(Studenti studentiByStudentiIdstudenti) {
        this.studentiByStudentiIdstudenti = studentiByStudentiIdstudenti;
    }
    public Studenti getStudentiByIdstudenti() {
        return this.studentiByIdstudenti;
    }
    
    public void setStudentiByIdstudenti(Studenti studentiByIdstudenti) {
        this.studentiByIdstudenti = studentiByIdstudenti;
    }
    public Subiecte getSubiecte() {
        return this.subiecte;
    }
    
    public void setSubiecte(Subiecte subiecte) {
        this.subiecte = subiecte;
    }
    public Date getDataExamen() {
        return this.dataExamen;
    }
    
    public void setDataExamen(Date dataExamen) {
        this.dataExamen = dataExamen;
    }
    public Integer getPuncteCredit() {
        return this.puncteCredit;
    }
    
    public void setPuncteCredit(Integer puncteCredit) {
        this.puncteCredit = puncteCredit;
    }




}


