package pojo;
// Generated Dec 31, 2018 12:01:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Studenti generated by hbm2java
 */
public class Studenti  implements java.io.Serializable {


     private Integer idstudenti;
     private String nume;
     private String prenume;
     private String grupa;
     private Set<Disciplina> disciplinasForStudentiIdstudenti = new HashSet<Disciplina>(0);
     private Set<Disciplina> disciplinasForIdstudenti = new HashSet<Disciplina>(0);

    public Studenti() {
    }

    public Studenti(String nume, String prenume, String grupa, Set<Disciplina> disciplinasForStudentiIdstudenti, Set<Disciplina> disciplinasForIdstudenti) {
       this.nume = nume;
       this.prenume = prenume;
       this.grupa = grupa;
       this.disciplinasForStudentiIdstudenti = disciplinasForStudentiIdstudenti;
       this.disciplinasForIdstudenti = disciplinasForIdstudenti;
    }
   
    public Integer getIdstudenti() {
        return this.idstudenti;
    }
    
    public void setIdstudenti(Integer idstudenti) {
        this.idstudenti = idstudenti;
    }
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    public String getPrenume() {
        return this.prenume;
    }
    
    public void setPrenume(String prenume) {
        this.prenume = prenume;
    }
    public String getGrupa() {
        return this.grupa;
    }
    
    public void setGrupa(String grupa) {
        this.grupa = grupa;
    }
    public Set<Disciplina> getDisciplinasForStudentiIdstudenti() {
        return this.disciplinasForStudentiIdstudenti;
    }
    
    public void setDisciplinasForStudentiIdstudenti(Set<Disciplina> disciplinasForStudentiIdstudenti) {
        this.disciplinasForStudentiIdstudenti = disciplinasForStudentiIdstudenti;
    }
    public Set<Disciplina> getDisciplinasForIdstudenti() {
        return this.disciplinasForIdstudenti;
    }
    
    public void setDisciplinasForIdstudenti(Set<Disciplina> disciplinasForIdstudenti) {
        this.disciplinasForIdstudenti = disciplinasForIdstudenti;
    }




}


