package pojo;
// Generated Dec 31, 2018 12:01:50 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subiecte generated by hbm2java
 */
public class Subiecte  implements java.io.Serializable {


     private Integer idsubiecte;
     private String tip;
     private String nrIntrebari;
     private Set<Disciplina> disciplinas = new HashSet<Disciplina>(0);

    public Subiecte() {
    }

    public Subiecte(String tip, String nrIntrebari, Set<Disciplina> disciplinas) {
       this.tip = tip;
       this.nrIntrebari = nrIntrebari;
       this.disciplinas = disciplinas;
    }
   
    public Integer getIdsubiecte() {
        return this.idsubiecte;
    }
    
    public void setIdsubiecte(Integer idsubiecte) {
        this.idsubiecte = idsubiecte;
    }
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }
    public String getNrIntrebari() {
        return this.nrIntrebari;
    }
    
    public void setNrIntrebari(String nrIntrebari) {
        this.nrIntrebari = nrIntrebari;
    }
    public Set<Disciplina> getDisciplinas() {
        return this.disciplinas;
    }
    
    public void setDisciplinas(Set<Disciplina> disciplinas) {
        this.disciplinas = disciplinas;
    }




}


